-- MySQL Script generated by MySQL Workbench
-- Sun Oct 21 20:22:51 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema UnlimitedEducation
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `UnlimitedEducation` ;

-- -----------------------------------------------------
-- Schema UnlimitedEducation
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `UnlimitedEducation` DEFAULT CHARACTER SET utf8 ;
USE `UnlimitedEducation` ;

-- -----------------------------------------------------
-- Table `UnlimitedEducation`.`Genders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UnlimitedEducation`.`Genders` ;

CREATE TABLE IF NOT EXISTS `UnlimitedEducation`.`Genders` (
  `id_gender` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_gender`),
  UNIQUE INDEX `id_gender_UNIQUE` (`id_gender` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UnlimitedEducation`.`Localities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UnlimitedEducation`.`Localities` ;

CREATE TABLE IF NOT EXISTS `UnlimitedEducation`.`Localities` (
  `id_locality` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_locality`),
  UNIQUE INDEX `id_locality_UNIQUE` (`id_locality` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UnlimitedEducation`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UnlimitedEducation`.`Users` ;

CREATE TABLE IF NOT EXISTS `UnlimitedEducation`.`Users` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `age` INT NOT NULL,
  `city` VARCHAR(255) NOT NULL,
  `id_gender_fk` INT NOT NULL,
  `id_locality_fk` INT NOT NULL,
  `created_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `id_user_UNIQUE` (`id_user` ASC) VISIBLE,
  INDEX `fk_users_localities_idx` (`id_locality_fk` ASC) VISIBLE,
  INDEX `fk_users_genders_idx` (`id_gender_fk` ASC) VISIBLE,
  CONSTRAINT `fk_users_genders`
    FOREIGN KEY (`id_gender_fk`)
    REFERENCES `UnlimitedEducation`.`Genders` (`id_gender`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_localities`
    FOREIGN KEY (`id_locality_fk`)
    REFERENCES `UnlimitedEducation`.`Localities` (`id_locality`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `UnlimitedEducation`.`Categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UnlimitedEducation`.`Categories` ;

CREATE TABLE IF NOT EXISTS `UnlimitedEducation`.`Categories` (
  `id_category` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_category`),
  UNIQUE INDEX `id_category_UNIQUE` (`id_category` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UnlimitedEducation`.`Themes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UnlimitedEducation`.`Themes` ;

CREATE TABLE IF NOT EXISTS `UnlimitedEducation`.`Themes` (
  `id_theme` INT NOT NULL,
  `tittle` VARCHAR(255) NOT NULL,
  `id_category_fk` INT NOT NULL,
  `icon` VARCHAR(45) NULL,
  PRIMARY KEY (`id_theme`),
  UNIQUE INDEX `id_theme_UNIQUE` (`id_theme` ASC) VISIBLE,
  INDEX `fk_themes_categories_idx` (`id_category_fk` ASC) VISIBLE,
  CONSTRAINT `fk_themes_categories`
    FOREIGN KEY (`id_category_fk`)
    REFERENCES `UnlimitedEducation`.`Categories` (`id_category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UnlimitedEducation`.`Courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UnlimitedEducation`.`Courses` ;

CREATE TABLE IF NOT EXISTS `UnlimitedEducation`.`Courses` (
  `id_course` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `author` VARCHAR(255) NOT NULL,
  `icon` VARCHAR(45) NULL,
  `id_theme_fk` INT NOT NULL,
  PRIMARY KEY (`id_course`),
  UNIQUE INDEX `id_course_UNIQUE` (`id_course` ASC) VISIBLE,
  INDEX `fk_courses_themes_idx` (`id_theme_fk` ASC) VISIBLE,
  CONSTRAINT `fk_courses_themes`
    FOREIGN KEY (`id_theme_fk`)
    REFERENCES `UnlimitedEducation`.`Themes` (`id_theme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UnlimitedEducation`.`CoursesTaken`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UnlimitedEducation`.`CoursesTaken` ;

CREATE TABLE IF NOT EXISTS `UnlimitedEducation`.`CoursesTaken` (
  `id_takencurse` INT NOT NULL,
  `progress` INT NULL,
  `id_course_fk` INT NOT NULL,
  `id_user_fk` INT NOT NULL,
  PRIMARY KEY (`id_takencurse`),
  UNIQUE INDEX `id_coursestaken_UNIQUE` (`id_takencurse` ASC) VISIBLE,
  INDEX `fk_coursestaken_courses_idx` (`id_course_fk` ASC) VISIBLE,
  INDEX `fk_coursestaken_users_idx` (`id_user_fk` ASC) VISIBLE,
  CONSTRAINT `fk_coursestaken_courses`
    FOREIGN KEY (`id_course_fk`)
    REFERENCES `UnlimitedEducation`.`Courses` (`id_course`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_coursestaken_users`
    FOREIGN KEY (`id_user_fk`)
    REFERENCES `UnlimitedEducation`.`Users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UnlimitedEducation`.`Slides`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UnlimitedEducation`.`Slides` ;

CREATE TABLE IF NOT EXISTS `UnlimitedEducation`.`Slides` (
  `id_slide` INT NOT NULL,
  `description` VARCHAR(255) NULL,
  `id_slide_fk` INT NOT NULL,
  PRIMARY KEY (`id_slide`),
  UNIQUE INDEX `id_slide_UNIQUE` (`id_slide` ASC) VISIBLE,
  INDEX `fk_slides_slides_idx` (`id_slide_fk` ASC) VISIBLE,
  CONSTRAINT `fk_slides_slides`
    FOREIGN KEY (`id_slide_fk`)
    REFERENCES `UnlimitedEducation`.`Slides` (`id_slide`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UnlimitedEducation`.`QuestionTypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UnlimitedEducation`.`QuestionTypes` ;

CREATE TABLE IF NOT EXISTS `UnlimitedEducation`.`QuestionTypes` (
  `id_questiontypes` INT NOT NULL,
  `type` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_questiontypes`),
  UNIQUE INDEX `id_questiontypes_UNIQUE` (`id_questiontypes` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UnlimitedEducation`.`Questions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UnlimitedEducation`.`Questions` ;

CREATE TABLE IF NOT EXISTS `UnlimitedEducation`.`Questions` (
  `id_question` INT NOT NULL,
  `question` VARCHAR(255) NOT NULL,
  `id_questiontype_fk` INT NOT NULL,
  `id_slide_fk` INT NOT NULL,
  UNIQUE INDEX `id_question_UNIQUE` (`id_question` ASC) VISIBLE,
  PRIMARY KEY (`id_question`),
  INDEX `fk_questions_slides_idx` (`id_slide_fk` ASC) VISIBLE,
  INDEX `fk_questions_questiontypes_idx` (`id_questiontype_fk` ASC) VISIBLE,
  CONSTRAINT `fk_questions_slides`
    FOREIGN KEY (`id_slide_fk`)
    REFERENCES `UnlimitedEducation`.`Slides` (`id_slide`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_questions_questiontypes`
    FOREIGN KEY (`id_questiontype_fk`)
    REFERENCES `UnlimitedEducation`.`QuestionTypes` (`id_questiontypes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UnlimitedEducation`.`Answers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UnlimitedEducation`.`Answers` ;

CREATE TABLE IF NOT EXISTS `UnlimitedEducation`.`Answers` (
  `id_answers` INT NOT NULL,
  `answers` VARCHAR(255) NOT NULL,
  `value` INT NOT NULL,
  `id_question_fk` INT NOT NULL,
  PRIMARY KEY (`id_answers`),
  UNIQUE INDEX `id_answers_UNIQUE` (`id_answers` ASC) VISIBLE,
  INDEX `fk_answers_questions_idx` (`id_question_fk` ASC) VISIBLE,
  CONSTRAINT `fk_answers_questions`
    FOREIGN KEY (`id_question_fk`)
    REFERENCES `UnlimitedEducation`.`Questions` (`id_question`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UnlimitedEducation`.`AnswersByUser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UnlimitedEducation`.`AnswersByUser` ;

CREATE TABLE IF NOT EXISTS `UnlimitedEducation`.`AnswersByUser` (
  `id_answersbyuser` INT NOT NULL,
  `id_takencourse_fk` INT NULL,
  `id_answer_fk` INT NULL,
  PRIMARY KEY (`id_answersbyuser`),
  UNIQUE INDEX `id_answersbyuser_UNIQUE` (`id_answersbyuser` ASC) VISIBLE,
  INDEX `fk_answersbyuser_answer_idx` (`id_answer_fk` ASC) VISIBLE,
  INDEX `fk_answersbyuser_coursestaken_idx` (`id_takencourse_fk` ASC) VISIBLE,
  CONSTRAINT `fk_answersbyuser_answer`
    FOREIGN KEY (`id_answer_fk`)
    REFERENCES `UnlimitedEducation`.`Answers` (`id_answers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_answersbyuser_coursestaken`
    FOREIGN KEY (`id_takencourse_fk`)
    REFERENCES `UnlimitedEducation`.`CoursesTaken` (`id_takencurse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UnlimitedEducation`.`Foudations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UnlimitedEducation`.`Foudations` ;

CREATE TABLE IF NOT EXISTS `UnlimitedEducation`.`Foudations` (
  `id_foudations` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `phone` VARCHAR(255) NOT NULL,
  `id_course_fk` INT NOT NULL,
  PRIMARY KEY (`id_foudations`),
  INDEX `fk_foundations_courses_idx` (`id_course_fk` ASC) VISIBLE,
  CONSTRAINT `fk_foundations_courses`
    FOREIGN KEY (`id_course_fk`)
    REFERENCES `UnlimitedEducation`.`Courses` (`id_course`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UnlimitedEducation`.`Challenges`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UnlimitedEducation`.`Challenges` ;

CREATE TABLE IF NOT EXISTS `UnlimitedEducation`.`Challenges` (
  `id_challenge` INT NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `level` INT NOT NULL,
  `id_course_fk` INT NOT NULL,
  PRIMARY KEY (`id_challenge`),
  INDEX `fk_challenges_courses_idx` (`id_course_fk` ASC) VISIBLE,
  CONSTRAINT `fk_challenges_courses`
    FOREIGN KEY (`id_course_fk`)
    REFERENCES `UnlimitedEducation`.`Courses` (`id_course`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UnlimitedEducation`.`ChallengesTaken`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UnlimitedEducation`.`ChallengesTaken` ;

CREATE TABLE IF NOT EXISTS `UnlimitedEducation`.`ChallengesTaken` (
  `id_challengetaken` INT NOT NULL,
  `completed` TINYINT NOT NULL,
  `id_challenge_fk` INT NOT NULL,
  `id_user_fk` INT NOT NULL,
  PRIMARY KEY (`id_challengetaken`),
  UNIQUE INDEX `id_challengetaken_UNIQUE` (`id_challengetaken` ASC) VISIBLE,
  INDEX `fk_challengestaken_users_idx` (`id_user_fk` ASC) VISIBLE,
  INDEX `fk_challengestaken_challenges_idx` (`id_challenge_fk` ASC) VISIBLE,
  CONSTRAINT `fk_challengestaken_users`
    FOREIGN KEY (`id_user_fk`)
    REFERENCES `UnlimitedEducation`.`Users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_challengestaken_challenges`
    FOREIGN KEY (`id_challenge_fk`)
    REFERENCES `UnlimitedEducation`.`Challenges` (`id_challenge`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
